version : "3.8"
services:
  chatGpt_svc:
    image : haythambammou/test_tech:chatgpt
    ports:
      - 8080:8080
    environment:
      - path=/usr/app/data/output.json
      - API_KEY=${API_KEY}
    volumes:
      - file:/usr/app/data
volumes:
  file: {}